package communication;

public enum MessageType {

	/* Message from Server */
	CONFIRM_IP, WAIT_RESPONSE, SUCCEED, NOT_SUCCEED,
	ERROR, EXIT, LOGIN, LOGOUT, UPDATE, GET_ORDERS,
	GET_SELECTED_ORDER,GET_USERS, GET_PREMADE_ITEMS,
	GET_ACCOUNT_DETAILS, GET_SELFASSEMBLY_ITEMS,
	GET_STORE_NAME, INSERT_NEW_ORDER,GET_STORE_ID,
	GET_ORDER_BY_ID, GET_USERID_BY_ORDERID,
	INSERT_NEW_COMPLAIN, GET_SURVEY_NUMBER,
	INSERT_NEW_SURVEY, CHECK_EXIST_QOMPLAIN,
	CHECK_ORDER_BY_USERID, CHECK_IF_USERNAME_EXIST,
	INSERT_NEW_USER, INSERT_NEW_ACCOUNT, GET_COMPLAINTS,
	GET_COMPLAINT_BY_ID, UPDATE_REFUND, UPDATE_STATUS_COMPLAINT,
	GET_SINGLE_DELIVERY, UPDATE_CATALOG, ADD_NEW_ITEM, DELETE_ITEM,
	CANCEL_ORDER, UPDATE_USED_REFUND,
	GET_SINGLE_DELIVERY_BY_ORDER_ID,
	UPDATE_DELIVERY_STATUS,
	INSERT_TO_DELIVERY_TABLE,
	UPDATE_REFUND_BY_ORDERID,
	VIEW_SELF_DELIVERY_DETAILS,
	VIEW_SELF_DELIVERY_DETAILS_BY_ORDERID,
	GET_SINGLE_DELIVERY_BY_STORE_ID, GET_SURVEY_ANSWERS, GET_STORE_ORDERS,
	INCOME_REPORT, GET_STORE_ID_BY_WORKER_ID, GRAPH_STATISTICS,
	GET_STORE_NAME_BY_ID, SAVE_ANALYSIS;

}