package communication;

public enum MessageType {

    /*Message from Server*/
    CONFIRM_IP, WAIT_RESPONSE, SUCCEED, NOT_SUCCEED, ERROR, EXIT,LOGIN, LOGOUT, UPDATE, GET_ORDERS, GET_SELECTED_ORDER, GET_USERS, GET_PREMADE_ITEMS, 
    GET_ACCOUNT_DETAILS, GET_SELFASSEMBLY_ITEMS,GET_STORE_NAME,INSERT_NEW_ORDER,GET_STORE_ID, GET_ORDER_BY_ID,GET_USERID_BY_ORDERID,INSERT_NEW_COMPLAIN;

}